# Generated by Django 5.1.1 on 2025-07-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0005_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='yNjuYd17OKN4ZNJxbFa4CZQpWGfqE1vH', editable=False, max_length=32, unique=True),
        ),
    ]
