# Generated by Django 5.1.1 on 2025-11-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0008_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='DOOGNixxIp8X8DyY37845zIUsGy5z3TP', editable=False, max_length=32, unique=True),
        ),
    ]
